<a href="https://colab.research.google.com/github/rename-z/Deep-Learning/blob/master/Zero%20to%20GANs/Linear%20Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Linear Regression with PyTorch**

We'll create a model that predicts crop yields for apples and oranges (*target variables*) by looking at the average temperature, rainfall and humidity (*input variables or features*) in a region. Here's the training data:

![linear-regression-training-data](https://i.imgur.com/6Ujttb4.png)

In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

```
yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2
```

In [1]:
import numpy as np
import torch

In [7]:
# Input (temperature, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [8]:
# Target (Apples, Oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [9]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [10]:
# Weight and Biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)

print(w)
print(b)

tensor([[ 1.6768,  1.0685,  0.5240],
        [-0.1598,  1.0706,  0.6236]], requires_grad=True)
tensor([0.1355, 0.1685], requires_grad=True)


In [14]:
def model(x) :
  return x @ w.t() + b

In [15]:
preds = model(inputs)
print(preds)

tensor([[216.6655,  87.0457],
        [280.2908, 119.7468],
        [319.5904, 165.8922],
        [236.5058,  52.9746],
        [255.0924, 135.5694]], grad_fn=<AddBackward0>)


In [16]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [17]:
def mse(t1, t2) :
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()

In [18]:
loss = mse(targets, preds)
loss

tensor(17716.5176, grad_fn=<DivBackward0>)

In [19]:
loss.backward()

In [20]:
print(w)
print(w.grad)

tensor([[ 1.6768,  1.0685,  0.5240],
        [-0.1598,  1.0706,  0.6236]], requires_grad=True)
tensor([[15937.8730, 15801.1816,  9976.1289],
        [ 1716.9213,  1895.3799,  1118.2845]])


In [21]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [22]:
# 1.Generate predictions
preds = model(inputs)
preds

tensor([[216.6655,  87.0457],
        [280.2908, 119.7468],
        [319.5904, 165.8922],
        [236.5058,  52.9746],
        [255.0924, 135.5694]], grad_fn=<AddBackward0>)

In [23]:
# 2.Calculate the loss
loss = mse(preds, targets)
loss

tensor(17716.5176, grad_fn=<DivBackward0>)

In [24]:
# 3.Compute the gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[15937.8730, 15801.1816,  9976.1289],
        [ 1716.9213,  1895.3799,  1118.2845]])
tensor([185.4290,  20.2457])


In [25]:
# 4 & 5.Adjust weights & reset gradients
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [26]:
print(w)
print(b)

tensor([[ 1.5175,  0.9105,  0.4242],
        [-0.1770,  1.0516,  0.6124]], requires_grad=True)
tensor([0.1337, 0.1683], requires_grad=True)


In [27]:
preds = model(inputs)
preds

tensor([[190.1525,  84.0413],
        [245.4957, 115.8006],
        [278.7628, 161.2098],
        [209.7616,  49.9943],
        [221.9410, 131.7822]], grad_fn=<AddBackward0>)

In [28]:
loss = mse(preds, targets)
loss

tensor(12152.5518, grad_fn=<DivBackward0>)

In [29]:
# Train for multiple epochs
for i in range(100) :
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [30]:
preds = model(inputs)
loss = mse(preds, targets)
print(preds)
print(loss)

tensor([[ 63.6306,  70.4171],
        [ 82.5744,  98.0719],
        [107.4633, 138.6945],
        [ 58.1383,  37.2115],
        [ 80.9589, 114.5362]], grad_fn=<AddBackward0>)
tensor(204.6735, grad_fn=<DivBackward0>)


In [31]:
preds

tensor([[ 63.6306,  70.4171],
        [ 82.5744,  98.0719],
        [107.4633, 138.6945],
        [ 58.1383,  37.2115],
        [ 80.9589, 114.5362]], grad_fn=<AddBackward0>)

In [32]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

### *Linear Regression using PyTorch build-ins*

In [33]:
import torch.nn as nn

In [35]:
# Inputs (Temperature, Rainfall, Humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58],
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]],
                  dtype='float32')

# Target (Apple, Orange)
targets = np.array([[56, 70],[81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

In [36]:
# converting numpy array to PyTorch tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [47]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F

In [38]:
# Dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [40]:
# Define data Loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [42]:
for xb, yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.]])
tensor([[ 56.,  70.],
        [103., 119.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.]])


In [43]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4686, -0.3543,  0.1407],
        [-0.5302,  0.5652, -0.3334]], requires_grad=True)
Parameter containing:
tensor([ 0.2626, -0.0742], requires_grad=True)


In [44]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4686, -0.3543,  0.1407],
         [-0.5302,  0.5652, -0.3334]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2626, -0.0742], requires_grad=True)]

In [45]:
# Generate Prediction
preds = model(inputs)
preds

tensor([[-51.6376, -15.2460],
        [-64.5594, -19.9213],
        [-79.8291,  10.1992],
        [-57.5673, -42.1869],
        [-56.2405,  -5.7351],
        [-51.6376, -15.2460],
        [-64.5594, -19.9213],
        [-79.8291,  10.1992],
        [-57.5673, -42.1869],
        [-56.2405,  -5.7351],
        [-51.6376, -15.2460],
        [-64.5594, -19.9213],
        [-79.8291,  10.1992],
        [-57.5673, -42.1869],
        [-56.2405,  -5.7351]], grad_fn=<AddmmBackward>)

In [48]:
loss_fn = F.mse_loss

In [49]:
loss = loss_fn(model(inputs), targets)
loss

tensor(16279.3213, grad_fn=<MseLossBackward>)

In [50]:
# Optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [51]:
def fit(num_epochs, model, loss_fn, opt, train_dl) :
  for epoch in range(num_epochs) :
    for xb, yb in train_dl :
      preds = model(xb)
      loss = loss_fn(preds, yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if (epoch+1) % 10 == 0 :
      print('Epoch [{}/{}], Loss : {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [53]:
fit (100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss : 150.4914
Epoch [20/100], Loss : 87.3038
Epoch [30/100], Loss : 63.8155
Epoch [40/100], Loss : 93.5871
Epoch [50/100], Loss : 69.3222
Epoch [60/100], Loss : 48.9913
Epoch [70/100], Loss : 39.5407
Epoch [80/100], Loss : 39.9831
Epoch [90/100], Loss : 41.6630
Epoch [100/100], Loss : 28.6583


In [55]:
preds = model(inputs)
preds

tensor([[ 58.1396,  71.1275],
        [ 82.6213,  95.7964],
        [116.2436, 143.5037],
        [ 26.4149,  40.6748],
        [ 99.5772, 108.4539],
        [ 58.1396,  71.1275],
        [ 82.6213,  95.7964],
        [116.2436, 143.5037],
        [ 26.4149,  40.6748],
        [ 99.5772, 108.4539],
        [ 58.1396,  71.1275],
        [ 82.6213,  95.7964],
        [116.2436, 143.5037],
        [ 26.4149,  40.6748],
        [ 99.5772, 108.4539]], grad_fn=<AddmmBackward>)

In [56]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])