<a href="https://colab.research.google.com/github/rename-z/Deep-Learning/blob/master/Zero%20to%20GANs/PyTorch%20Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **PyTorch Basics : Tensors & Gradients**

In [1]:
# !conda install pytorch cpuonly -c pytorch -y

/bin/bash: conda: command not found


In [2]:
import torch

In [3]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [6]:
t3 = torch.tensor([[5., 6],
                   [7, 8],
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
t4 = torch.tensor([
                   [[12, 17, 11],
                    [15, 16, 29]],
                   [[21, 22., 56],
                    [25, 64, 68]]
])
t4

tensor([[[12., 17., 11.],
         [15., 16., 29.]],

        [[21., 22., 56.],
         [25., 64., 68.]]])

In [8]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [9]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [10]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [11]:
print(t4)
t4.shape

tensor([[[12., 17., 11.],
         [15., 16., 29.]],

        [[21., 22., 56.],
         [25., 64., 68.]]])


torch.Size([2, 2, 3])

In [12]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [13]:
y = x * w + b
y

tensor(17., grad_fn=<AddBackward0>)

In [14]:
y.backward()

In [15]:
print('dy/dx : ', x.grad)
print('dy/dw : ', w.grad)
print('dy/db : ', b.grad)

dy/dx :  None
dy/dw :  tensor(3.)
dy/db :  tensor(1.)


### *Interoperability with Numpy*

In [16]:
import numpy as np

In [17]:
x = np.array([[1, 2],
              [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [18]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [19]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [20]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])